require:
  - rubocop-capybara
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb
    - tmp/**/*
    - vendor/**/*

Metrics/AbcSize:
  Exclude:
    - db/**/*
Metrics/BlockLength:
  Exclude:
    - config/**/*
    - db/**/*
    - lib/tasks/**/*
Metrics/ClassLength:
  Max: 200
Metrics/MethodLength:
  Exclude:
    - db/**/*

RSpec/ExampleLength:
  Max: 10
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Exclude:
    - app/controllers/**/*
    - test/**/*
    - db/**/*
Style/EmptyMethod:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/SymbolProc:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Enabled: false
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
