require:
  - rubocop-capybara
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb
    - tmp/**/*
    - vendor/**/*

Metrics/AbcSize:
  Exclude:
    - db/**/*
Metrics/MethodLength:
  Exclude:
    - db/**/*

RSpec/MultipleExpectations:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Exclude:
    - app/controllers/**/*
    - test/**/*
    - db/**/*
Style/EmptyMethod:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
