name: File test

on: push

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    environment: main
    steps:
      - uses: actions/checkout@v3
      - name: Create test file
        env:
          TEST_FILE_BASE64: ${{ secrets.TEST_FILE_BASE64 }}
        run: echo $TEST_FILE_BASE64 | base64 -d > test.txt
      - run: cat test.txt
